### ISSUE TITLE
Unnatural method of quitting app

### ISSUE THREAD

**Issue by hanaral** [candiedoperation/marquer#2]
Firstly, nice work!
Currently the method of closing the window, and therefore the app, is presented in a row of buttons along with the app's central functions (open file + select drive) - closing the app isn't really a function, it's a passive thing that is abstract from the purpose of the app's landing screen!
I could easily see it having a close button in the usual location (if the app were more of a 'widget', it could also be a dialogue btn like elementary Screenshot)

**Comment by candiedoperation** [comment]
@hanaral, Requesting you to have a look at the linked pull request. I've implemented suggestions related to the close app button.
